# Generated by Django 3.2.7 on 2021-10-06 12:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None)),
                ('address', models.CharField(max_length=400)),
                ('date', models.DateTimeField(blank=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(max_length=600)),
            ],
        ),
    ]
