# Generated by Django 3.2.7 on 2021-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_clientleads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleads',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
