# Generated by Django 3.2.7 on 2021-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_clientleads_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleads',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
