# Generated by Django 3.2.7 on 2021-10-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_clientleads_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleads',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
