# Generated by Django 3.2.7 on 2021-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_galleryupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('testimony', models.TextField(max_length=400)),
                ('profile', models.ImageField(upload_to='images/testimonies')),
            ],
        ),
    ]
